try:
    a = 340/10

except Exception as e:
    print(e)
    
# Gets excute when no error in the try block
else:
    print("Hey i am good")